import { sql } from "drizzle-orm";
import { check, index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const activities = sqliteTable("activities", {
  id: text("id").primaryKey(),
  slug: text("slug").notNull(),
  title: text("title").notNull(),
  sport: text("sport").notNull(),
  municipality: text("municipality").notNull(),
  venue: text("venue").notNull(),
  summary: text("summary").notNull(),
  dateStatus: text("date_status", { enum: ["confirmed", "tbd"] }).notNull(),
  startAt: integer("start_at"),
  endAt: integer("end_at"),
  eventStatus: text("event_status", { enum: ["scheduled", "postponed", "cancelled"] }).notNull(),
  editorialStatus: text("editorial_status", { enum: ["draft", "scheduled", "published", "archived"] }).notNull(),
  publishAt: integer("publish_at"),
  unpublishAt: integer("unpublish_at"),
  featured: integer("featured", { mode: "boolean" }).notNull().default(false),
  imageUrl: text("image_url").notNull().default(""),
  videoUrl: text("video_url").notNull().default(""),
  registrationUrl: text("registration_url").notNull().default(""),
  createdBy: text("created_by").notNull(),
  updatedBy: text("updated_by").notNull(),
  createdAt: integer("created_at").notNull().default(sql`(unixepoch())`),
  updatedAt: integer("updated_at").notNull().default(sql`(unixepoch())`),
  version: integer("version").notNull().default(1),
}, (table) => [
  uniqueIndex("activities_slug_unique").on(table.slug),
  index("activities_visibility_idx").on(table.editorialStatus, table.publishAt, table.unpublishAt),
  index("activities_start_idx").on(table.startAt),
  check("activities_date_status_check", sql`${table.dateStatus} in ('confirmed','tbd')`),
  check("activities_event_status_check", sql`${table.eventStatus} in ('scheduled','postponed','cancelled')`),
  check("activities_editorial_status_check", sql`${table.editorialStatus} in ('draft','scheduled','published','archived')`),
  check("activities_confirmed_date_check", sql`${table.dateStatus} != 'confirmed' or ${table.startAt} is not null`),
  check("activities_end_check", sql`${table.endAt} is null or (${table.startAt} is not null and ${table.endAt} >= ${table.startAt})`),
  check("activities_scheduled_publish_check", sql`${table.editorialStatus} != 'scheduled' or ${table.publishAt} is not null`),
  check("activities_unpublish_check", sql`${table.unpublishAt} is null or ${table.publishAt} is null or ${table.unpublishAt} > ${table.publishAt}`),
  check("activities_version_check", sql`${table.version} >= 1`),
]);

export const activitySubmissions = sqliteTable("activity_submissions", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  sport: text("sport").notNull(),
  municipality: text("municipality").notNull(),
  venue: text("venue").notNull(),
  summary: text("summary").notNull(),
  dateStatus: text("date_status", { enum: ["confirmed", "tbd"] }).notNull(),
  startAt: integer("start_at"),
  endAt: integer("end_at"),
  imageUrl: text("image_url").notNull().default(""),
  videoUrl: text("video_url").notNull().default(""),
  registrationUrl: text("registration_url").notNull().default(""),
  contactName: text("contact_name").notNull(),
  contactEmail: text("contact_email").notNull(),
  contactPhone: text("contact_phone").notNull().default(""),
  consent: integer("consent", { mode: "boolean" }).notNull(),
  status: text("status", { enum: ["pending", "accepted", "rejected"] }).notNull().default("pending"),
  adminNote: text("admin_note").notNull().default(""),
  acceptedActivityId: text("accepted_activity_id").references(() => activities.id, { onDelete: "set null" }),
  reviewedBy: text("reviewed_by"),
  reviewedAt: integer("reviewed_at"),
  createdAt: integer("created_at").notNull().default(sql`(unixepoch())`),
  updatedAt: integer("updated_at").notNull().default(sql`(unixepoch())`),
}, (table) => [
  index("activity_submissions_status_idx").on(table.status, table.createdAt),
  check("activity_submissions_date_status_check", sql`${table.dateStatus} in ('confirmed','tbd')`),
  check("activity_submissions_status_check", sql`${table.status} in ('pending','accepted','rejected')`),
  check("activity_submissions_consent_check", sql`${table.consent} = 1`),
]);

export const adminLoginAttempts = sqliteTable("admin_login_attempts", {
  bucketKey: text("bucket_key").primaryKey(),
  failedCount: integer("failed_count").notNull().default(0),
  windowStartedAt: integer("window_started_at").notNull(),
  lockedUntil: integer("locked_until").notNull().default(0),
  updatedAt: integer("updated_at").notNull().default(sql`(unixepoch())`),
}, (table) => [
  index("admin_login_attempts_updated_idx").on(table.updatedAt),
  check("admin_login_attempts_failed_count_check", sql`${table.failedCount} >= 0`),
]);
